dist: xenial
sudo: required

language: python
python:
    - 3.5
    - 3.6
    - 3.7

env:
    TEST_ENV: travis

install:
    - sudo apt-get install libmpv1 -y --force-yes
    - pip install coveralls
    - pip install pytest flake8 pytest-cov pytest-asyncio sphinx_rtd_theme
    - pip install -e .

script:
    - make test

after_success:
  - coveralls
